### PR TITLE
Add react-bootstrap, bootstrap, react-router-dom

### PR DESCRIPTION
**Pull request by kirils**

### CODE REVIEW

**Comment by steveme** [comment]
Really don't want to have to use bootstrap if I can help it, and ideally we'd use connected-react-router and hook it into the redux store? Am trying to keep the number of dependencies down, and i'm not convinced bootstrap is necessary?

**Comment by steveme** [comment]
But even vanilla react-router and react-router-dom (without the connected-react-router) would be good, except don't have anywhere to route to yet.

**Comment by steveme** [comment]
The menu's do look nice though :) Can you get the colour scheme to match?

**Comment by steveme** [comment]
Do you think it's worth having to use bootstrap just to get the menus?

**Comment by kirils** [comment]
> Really don't want to have to use bootstrap if I can help it, and ideally we'd use connected-react-router and hook it into the redux store? Am trying to keep the number of dependencies down, and i'm not convinced bootstrap is necessary?

I can remove it but I think it is necessary to use some responsive design framework. The other options are https://semantic-ui.com/ or Material UI.

**Comment by kirils** [comment]
> But even vanilla react-router and react-router-dom (without the connected-react-router) would be good, except don't have anywhere to route to yet.

You can use it in the future when you have login, save as ...

**Comment by steveme** [comment]
Would load/save be different routes? The only routes I can think of might be /diagram/{diagramId} or something?

**Comment by kirils** [comment]
> Do you think it's worth having to use bootstrap just to get the menus?

Yes if you want to have full responsive website, not only the menu but if you don't want I can remove it. Also you should create full css style for each component.

**Comment by steveme** [comment]
Looking through the bootstraps components, apart from the menu's, there doesn't seem to be that much stuff that would be useful for an app like this? The closes thing I could find was
https://semantic-ui.com/modules/sidebar.html but even then it seems like quite far from the sort of stuff i'm trying to get in the sidebars? (I was hoping to get an IDE type feel, with panes you can drag about or dock, etc.)

**Comment by kirils** [comment]
> Looking through the bootstraps components, apart from the menu's, there doesn't seem to be that much stuff that would be useful for an app like this? The closes thing I could find was
> https://semantic-ui.com/modules/sidebar.html but even then it seems like quite far from the sort of stuff i'm trying to get in the sidebars? (I was hoping to get an IDE type feel, with panes you can drag about or dock, etc.)

Ok I'll remove Bootstrap and React router for now and will left only some mockup menu.

**Comment by steveme** [comment]
Pick something on the TODO list :)

**Comment by kirils** [comment]
> Pick something on the TODO list :)

Ok

**Pull request closed without merging**
